#!/bin/bash

#upload function with full update of content

git_up_del () {

	echo Commiting new files

#	history>$(date +%Y%m%d_%H_%M)_history.txt

	git add -A
	git commit -m $(date +%Y%m%d_%H_%M)
	git push origin master

}

#upload function without deleting

git_up () {

	echo Commiting updated files

#	history>$(date +%Y%m%d_%H_%M)_history.txt

	git add .
	git commit -m $(date +%Y%m%d_%H_%M)
	git push origin master
}

#download function

git_down () {

	echo Cloning files

	git clone https://github.com/RTUhacker/DMI__.git

}

# exit bash script function

quit () {
	exit
}

#function select from input value

func_select () {

	if [ -z "$input" ]
	then
		printf "\n STRING IS EMPTY \n"
		success=0
	elif [ "$input" = up_del ]
	then
		git_up_del
		success=1
	elif [ "$input" = down ]
	then
		git_down
		success=1
	elif [ "$input" = up ]
	then
		git_up
		success=1
	elif [ "$input" = quit ]
	then
		quit
		success=1
	else
		printf "\n WRONG INPUT! \n"
		success=0
	fi

}

#input function with repeat
get_input ()
{
	while [ $success -ne 1 ]
	do
		printf " ------------------------------ \n "
		printf "There are 4 functions: \n 1. up \n 2. up_del \n"
		printf " 3. down \n 4. quit \n Type function NAME here: "
		read input </dev/tty
		func_select $input
		printf "\n Your input was: $input \n \n"
	done
}



#using input function
	success=0
	get_input
