#!/bin/bash

#upload function with full update of content

git_up_del () {

	echo Commiting new files

	history>$(date +%Y%m%d_%H_%M)_history.txt

	git add -A
	git commit -m $(date +%Y%m%d_%H_%M)
	git push origin master

}

#upload function without deleting

git_up () {

	echo Commiting updated files

	history>$(date +%Y%m%d_%H_%M)_history.txt

	git add .
	git commit -m $(date +%Y%m%d_%H_%M)
	git push origin master
}

#download function

git_down () {

	echo Cloning files

	git clone https://github.com/RTUhacker/DMI__.git

}

#get input function

get_input () {

	if [ -z "$input" ]
	then
		echo string is empty
	elif [ "$input" = up_del ]
	then
		git_up_del
	elif [ "$input" = down ]
	then
		git_down
	elif [ "$input" = up ]
	then
		git_up
	elif [ "$input" = quit ]
	then
		quit
	else
		printf "Wrong function. Try: \n 1. up \n 2. up_del \n 3. down \n 4. quit \n"
	fi

}

get_input2 ()
{
	printf " ------------------------------ \n "
	printf "There are 4 functions: \n 1. up \n 2. up_del \n"
	printf " 3. down \n 4. quit \n Type function NAME here: "
	read input </dev/tty
	get_input $input
	echo $input
}



#using input function
	#get_input $*
	get_input2
